baseURL: https://mariorodriguez.xyz/
languageCode: es-mx
title: Mario Rodríguez
enableGitInfo: true
Paginate: 9
rssLimit: 20
copyright: CC BY-SA
menu:
  footer:
  - identifier: Email
    name: Email
    pre: "/img/icons/email.svg"
    post: "Mi email personal"
    url: "mailto:mario@mariorodriguez.xyz"
    weight: 100
  - identifier: Git
    name: Git
    pre: "/img/icons/git.svg"
    post: "Liga a mis repositorios personales"
    url: "https://git.mariorodriguez.xyz"
    weight: 110
  - identifier: Xmpp
    name: Xmpp
    pre: "/img/icons/xmpp.svg"
    post: "Chat para conversar"
    url: "xmpp:mra@trashserver.net"
    weight: 120
  - identifier: Feed
    name: RSS
    pre: "/img/icons/feed.svg" 
    post: "Sígueme por RSS"
    url: "/index.xml"
    weight: 130
