baseURL: https://mrodz07.github.io
languageCode: es-mx
title: Mario Rodríguez
enableGitInfo: true
Paginate: 9
rssLimit: 20
copyright: CC BY-SA
menu:
  footer:
  - identifier: Email
    name: Email
    pre: "/img/icons/email.svg"
    post: "Mi email personal"
    url: "mailto:mrodz_contacto@proton.me"
    weight: 100
  - identifier: Git
    name: Git
    pre: "/img/icons/git.svg"
    post: "Liga a mis repositorios personales"
    url: "https://github.com/mrodz07"
    weight: 110
  - identifier: Feed
    name: RSS
    pre: "/img/icons/feed.svg" 
    post: "Sígueme por RSS"
    url: "/blog/index.xml"
    weight: 130
